<?php
/**
 * @package   Angeo_LlmsTxt
 * @copyright Copyright (c) Angeo
 * @license   MIT
 */
declare(strict_types=1);

namespace Angeo\LlmsTxt\Model\Output;

use Angeo\LlmsTxt\Model\Config;

/**
 * Single source of truth for the attribution signature appended to generated
 * markdown output (llms.txt, llms-full.txt, and the on-the-fly .md mirrors).
 *
 * The signature is:
 *  - plain spec-compliant markdown (a horizontal rule + one paragraph), so it
 *    never breaks parsers that consume llms.txt;
 *  - NEVER emitted into JSONL — one JSON record per line is a hard format
 *    contract, comments would corrupt it;
 *  - controlled by the `angeo_llms/general/signature_enabled` flag (default
 *    on, can be switched off per store — see system.xml).
 *
 * Keeping the text here (instead of inlining it in generators) guarantees the
 * legacy pipeline, the single-pass pipeline, and the .md mirror controller all
 * emit byte-identical signatures.
 *
 * @since 3.3.0
 */
class Signature
{
    /**
     * Rendered exactly once at the very end of a generated markdown file.
     * Leading "\n" separates it from the last content section; trailing "\n"
     * keeps POSIX-friendly EOF.
     */
    public function forTxt(): string
    {
        return sprintf(
            "\n---\n\nGenerated by [Angeo LlmsTxt](%s) v%s — open-source AEO module for Magento 2 "
            . "(MIT). Free AI-visibility scan for your store: %s\n",
            'https://angeo.dev/?utm_source=llms-txt&utm_medium=signature',
            Config::MODULE_VERSION,
            'https://angeo.dev/scan?utm_source=llms-txt&utm_medium=signature'
        );
    }

    /**
     * Signature for the generated agents.md operator's manual. Same content
     * as {@see forTxt()} with its own utm_medium so the surface is
     * independently measurable.
     *
     * @since 3.4.0
     */
    public function forAgentsMd(): string
    {
        return sprintf(
            "\n---\n\nGenerated by [Angeo LlmsTxt](%s) v%s — open-source AEO module for Magento 2 "
            . "(MIT). Free AI-visibility scan for your store: %s\n",
            'https://angeo.dev/?utm_source=llms-txt&utm_medium=agents-md',
            Config::MODULE_VERSION,
            'https://angeo.dev/scan?utm_source=llms-txt&utm_medium=agents-md'
        );
    }

    /**
     * Signature for the on-the-fly /{url-key}.md mirrors. Same content as
     * {@see forTxt()} with a mirror-specific utm_medium so the two surfaces
     * can be measured independently.
     */
    public function forMdMirror(): string
    {
        return sprintf(
            "\n---\n\nGenerated by [Angeo LlmsTxt](%s) v%s — open-source AEO module for Magento 2 "
            . "(MIT). Free AI-visibility scan for your store: %s\n",
            'https://angeo.dev/?utm_source=llms-txt&utm_medium=md-mirror',
            Config::MODULE_VERSION,
            'https://angeo.dev/scan?utm_source=llms-txt&utm_medium=md-mirror'
        );
    }
}
