<?php
/**
 * @package   Angeo_LlmsTxt
 * @copyright Copyright (c) Angeo
 * @license   MIT
 */
declare(strict_types=1);

namespace Angeo\LlmsTxt\Model\Pipeline;

use Angeo\LlmsTxt\Api\EntityProviderInterface;
use Angeo\LlmsTxt\Api\FormatRendererInterface;
use Angeo\LlmsTxt\Api\GenerationStatusRepositoryInterface;
use Angeo\LlmsTxt\Api\OutputContextInterface;
use Angeo\LlmsTxt\Api\UrlResolverInterface;
use Angeo\LlmsTxt\Model\Config;
use Angeo\LlmsTxt\Model\Generator\GenerationSummary;
use Angeo\LlmsTxt\Model\Output\FilePathResolver;
use Angeo\LlmsTxt\Model\Output\OutputContextFactory;
use Angeo\LlmsTxt\Model\Output\AgentSurfacesBlock;
use Angeo\LlmsTxt\Model\Output\Signature;
use Angeo\LlmsTxt\Model\Output\SurfaceRegistry;
use Angeo\LlmsTxt\Model\Pipeline\ChangeDetector;
use Magento\Framework\App\Area;
use Magento\Framework\App\Filesystem\DirectoryList;
use Magento\Framework\Event\ManagerInterface as EventManagerInterface;
use Magento\Framework\Filesystem;
use Magento\Framework\Filesystem\Directory\WriteInterface;
use Magento\Framework\View\DesignInterface;
use Magento\Store\Api\Data\StoreInterface;
use Magento\Store\Model\App\Emulation;
use Magento\Store\Model\StoreManagerInterface;
use Psr\Log\LoggerInterface;

/**
 * The generation pipeline (single pass; the only pipeline since 4.0.0).
 *
 * For each eligible store the catalog is iterated EXACTLY ONCE:
 *  - frontend emulation is set up once,
 *  - the URL-rewrite map is read once,
 *  - every entity is loaded and sanitized once,
 *  - each {@see EntityProviderInterface} record is rendered by every enabled
 *    {@see FormatRendererInterface} into its own atomically-written stream.
 *
 * File names, on-disk layout, served URLs, status records, and the
 * angeo_llms_generation_before/after/failed events (dispatched per format)
 * are unchanged from 3.x.
 *
 * @since 3.2.0
 */
class SinglePassGenerator
{
    /**
     * @param EntityProviderInterface[] $entityProviders ordered via di.xml
     * @param FormatRendererInterface[] $renderers keyed by FORMAT_* code via di.xml
     */
    public function __construct(
        private readonly StoreManagerInterface $storeManager,
        private readonly Filesystem $filesystem,
        private readonly LoggerInterface $logger,
        private readonly Config $config,
        private readonly Emulation $emulation,
        private readonly DesignInterface $viewDesign,
        private readonly OutputContextFactory $contextFactory,
        private readonly UrlResolverInterface $urlResolver,
        private readonly EventManagerInterface $eventManager,
        private readonly GenerationStatusRepositoryInterface $statusRepository,
        private readonly FilePathResolver $pathResolver,
        private readonly array $entityProviders = [],
        private readonly array $renderers = [],
        ?Signature $signature = null,
        ?AgentSurfacesBlock $surfacesBlock = null,
        ?SurfaceRegistry $surfaceRegistry = null,
        ?ChangeDetector $changeDetector = null
    ) {
        // Kept nullable for manual instantiation in tests; di.xml always injects
        // all three explicitly (Magento does not auto-wire optional params).
        $this->signature = $signature ?? new Signature();
        $this->surfacesBlock = $surfacesBlock ?? new AgentSurfacesBlock();
        $this->surfaceRegistry = $surfaceRegistry;
        $this->changeDetector = $changeDetector;
    }

    /** @since 3.3.0 */
    private readonly Signature $signature;
    /** @since 3.4.0 */
    private readonly AgentSurfacesBlock $surfacesBlock;
    /** @since 3.4.0 */
    private readonly ?SurfaceRegistry $surfaceRegistry;
    /** @since 4.1.0 */
    private readonly ?ChangeDetector $changeDetector;

    /**
     * @param string|null $storeCode restrict to one store, or null for all
     * @param array<string, bool> $skip ['llms_txt' => true, ...]
     * @param bool $force Ignore the unchanged-since check and always rebuild.
     * @return array<string, GenerationSummary> keyed by format
     */
    public function generateAll(?string $storeCode = null, array $skip = [], bool $force = false): array
    {
        $summaries = [];
        foreach ($this->pathResolver->getFormats() as $format) {
            // agents.md is generated by its own standalone generator (store-level
            // metadata, not catalog content) — no pipeline summary for it.
            if ($format === OutputContextInterface::FORMAT_AGENTS_MD) {
                continue;
            }
            if (empty($skip[$format])) {
                $summaries[$format] = new GenerationSummary();
            }
        }

        if (!$this->config->isEnabled()) {
            $this->logger->info('[Angeo LlmsTxt] Module is disabled — generation skipped.');
            return $summaries;
        }

        $stores = $storeCode
            ? [$this->storeManager->getStore($storeCode)]
            : $this->storeManager->getStores();

        $directory = $this->filesystem->getDirectoryWrite(DirectoryList::MEDIA);
        $directory->create(FilePathResolver::SUB_DIR);

        foreach ($stores as $store) {
            $this->processStore($store, $directory, $summaries, $force);
        }

        return $summaries;
    }

    /**
     * @param array<string, GenerationSummary> $summaries
     */
    private function processStore(
        StoreInterface $store,
        WriteInterface $directory,
        array $summaries,
        bool $force = false
    ): void {
        $code = $store->getCode();
        $isActive = !method_exists($store, 'isActive') || $store->isActive();
        $storeEligible = $isActive && !$this->config->isStoreExcluded($store);

        // Decide which formats run for this store; clean up stale files for the rest.
        $activeFormats = [];
        foreach (array_keys($summaries) as $format) {
            if ($storeEligible && $this->isFormatEnabled($format, $store)) {
                $activeFormats[] = $format;
            } else {
                $this->deleteIfExists($directory, $this->pathResolver->getRelativePath($format, $code));
                $summaries[$format]->skip($code);
            }
        }
        if ($activeFormats === []) {
            return;
        }

        if (!$force && $this->isUnchanged($store, $directory, $activeFormats)) {
            foreach ($activeFormats as $format) {
                $summaries[$format]->skip($code);
            }
            $this->logger->info(sprintf(
                '[Angeo LlmsTxt] Nothing changed for store %s since the last run — skipped.',
                $code
            ));
            return;
        }

        $emulated   = false;
        $lockHandle = null;
        $lockPath   = FilePathResolver::SUB_DIR . '/store_' . $code . '.lock';
        $startedAt  = microtime(true);
        /** @var array<string, array{stream: \Magento\Framework\Filesystem\File\WriteInterface, tmp: string, final: string, bytes: int, items: int}> $streams */
        $streams = [];

        try {
            if (!$this->viewDesign->getArea()) {
                $this->viewDesign->setArea(Area::AREA_FRONTEND);
            }
            $this->emulation->startEnvironmentEmulation((int) $store->getId(), Area::AREA_FRONTEND, true);
            $emulated = true;

            $this->urlResolver->reset();
            $this->urlResolver->warmUp((int) $store->getId());

            // One per-store lock covers all format streams of this pass.
            $lockHandle = $this->acquireLock($directory, $lockPath);
            if ($lockHandle === null) {
                throw new \RuntimeException(sprintf('Generation already in progress for store %s', $code));
            }

            // One sanitation context for the whole pass (max verbosity).
            $context = $this->contextFactory->create(
                $store,
                OutputContextInterface::FORMAT_LLMS_FULL_TXT,
                OutputContextInterface::VERBOSITY_FULL
            );

            foreach ($activeFormats as $format) {
                $final = $this->pathResolver->getRelativePath($format, $code);
                $tmp   = $final . '.tmp';
                $streams[$format] = [
                    'stream' => $directory->openFile($tmp, 'w'),
                    'tmp'    => $tmp,
                    'final'  => $final,
                    'bytes'  => 0,
                    'items'  => 0,
                ];
                $this->renderer($format)->reset();

                $this->eventManager->dispatch('angeo_llms_generation_before', [
                    'store'   => $store,
                    'format'  => $format,
                    'context' => $context,
                ]);
            }

            // ── THE single pass ─────────────────────────────────────────────
            foreach ($this->entityProviders as $provider) {
                if (!$provider instanceof EntityProviderInterface || !$provider->isApplicable($context)) {
                    continue;
                }
                try {
                    foreach ($provider->provide($context) as $record) {
                        foreach ($streams as $format => &$s) {
                            $emittedAny = false;
                            foreach ($this->renderer($format)->render($record, $context) as $chunk) {
                                if ($chunk === '') {
                                    continue;
                                }
                                $s['bytes'] += $s['stream']->write($chunk);
                                $emittedAny = true;
                            }
                            if ($emittedAny) {
                                $s['items']++;
                            }
                        }
                        unset($s);
                    }
                } catch (\Throwable $e) {
                    $this->logger->warning(sprintf(
                        '[Angeo LlmsTxt] Entity provider %s failed for store %s: %s',
                        $provider::class,
                        $code,
                        $e->getMessage()
                    ));
                }
            }

            foreach ($streams as $format => &$s) {
                foreach ($this->renderer($format)->finish($context) as $chunk) {
                    if ($chunk !== '') {
                        $s['bytes'] += $s['stream']->write($chunk);
                    }
                }
            }
            unset($s);

            // ── Agent-discovery hub block + attribution signature — markdown
            //    formats only, last chunks in the file. ──
            foreach ($streams as $format => &$s) {
                if ($format === OutputContextInterface::FORMAT_JSONL || $s['bytes'] === 0) {
                    continue;
                }
                if ($format === OutputContextInterface::FORMAT_LLMS_TXT) {
                    $block = $this->surfacesBlock->render(
                        $context->getBaseUrl(),
                        $this->surfaceRegistry !== null ? $this->surfaceRegistry->forStore($store) : []
                    );
                    if ($block !== '') {
                        $s['bytes'] += $s['stream']->write($block);
                    }
                }
                if ($this->config->isSignatureEnabled($store)) {
                    $s['bytes'] += $s['stream']->write($this->signature->forTxt());
                }
            }
            unset($s);

            // ── Finalize: close, atomic rename (or drop empty), record + events ─
            $duration = microtime(true) - $startedAt;
            foreach ($streams as $format => $s) {
                $s['stream']->close();
                if ($s['bytes'] === 0) {
                    $this->deleteIfExists($directory, $s['tmp']);
                } else {
                    $directory->renameFile($s['tmp'], $s['final']);
                }

                $this->statusRepository->recordSuccess($code, $format, $s['bytes'], $s['items'], $duration);
                $this->eventManager->dispatch('angeo_llms_generation_after', [
                    'store'    => $store,
                    'format'   => $format,
                    'file'     => $s['final'],
                    'bytes'    => $s['bytes'],
                    'items'    => $s['items'],
                    'duration' => $duration,
                ]);
                $summaries[$format]->success($code, $s['bytes'], $s['items'], $duration);

                $this->logger->info(sprintf(
                    '[Angeo LlmsTxt] [single-pass] Generated %s for store %s (%d bytes, %d items, %.2fs)',
                    $s['final'],
                    $code,
                    $s['bytes'],
                    $s['items'],
                    $duration
                ));
            }
            $streams = [];
        } catch (\Throwable $e) {
            // Close + discard any half-written tmp streams.
            foreach ($streams as $s) {
                try {
                    $s['stream']->close();
                    $this->deleteIfExists($directory, $s['tmp']);
                } catch (\Throwable) {
                    // best-effort cleanup
                }
            }

            foreach ($activeFormats as $format) {
                $this->statusRepository->recordFailure($code, $format, $e->getMessage());
                $this->eventManager->dispatch('angeo_llms_generation_failed', [
                    'store'  => $store,
                    'format' => $format,
                    'error'  => $e->getMessage(),
                ]);
                $summaries[$format]->failure($code, $e->getMessage());
            }

            $this->logger->error(sprintf(
                '[Angeo LlmsTxt] [single-pass] Failed generation for store %s: %s',
                $code,
                $e->getMessage()
            ), ['exception' => $e]);
        } finally {
            $this->releaseLock($directory, $lockPath, $lockHandle);
            if ($emulated) {
                $this->emulation->stopEnvironmentEmulation();
            }
            $this->urlResolver->reset();
        }
    }

    /**
     * Whether a rebuild can be skipped: the feature is on, every active format
     * already has a file on disk, and nothing relevant has changed since the
     * OLDEST of their successful runs.
     *
     * The oldest is the right bound — if llms.txt ran an hour ago but JSONL
     * failed yesterday, the store is not up to date.
     *
     * @param string[] $activeFormats
     * @since 4.1.0
     */
    private function isUnchanged(StoreInterface $store, WriteInterface $directory, array $activeFormats): bool
    {
        if ($this->changeDetector === null || !$this->config->isSkipUnchangedEnabled($store)) {
            return false;
        }

        $code = $store->getCode();
        $oldestSuccess = null;

        foreach ($activeFormats as $format) {
            if (!$directory->isExist($this->pathResolver->getRelativePath($format, $code))) {
                return false; // a missing file always rebuilds
            }
            $status = $this->statusRepository->get($code, $format);
            $successAt = $status?->getLastSuccessAt();
            if ($successAt === null) {
                return false;
            }
            if ($oldestSuccess === null || $successAt < $oldestSuccess) {
                $oldestSuccess = $successAt;
            }
        }

        if ($oldestSuccess === null) {
            return false;
        }

        $lastChange = $this->changeDetector->lastChangeAt($store);

        // null means detection failed — regenerate rather than risk stale files.
        return $lastChange !== null && $lastChange <= $oldestSuccess;
    }

    private function renderer(string $format): FormatRendererInterface
    {
        $renderer = $this->renderers[$format] ?? null;
        if (!$renderer instanceof FormatRendererInterface) {
            throw new \RuntimeException("No renderer registered for format {$format}");
        }
        return $renderer;
    }

    private function isFormatEnabled(string $format, StoreInterface $store): bool
    {
        return match ($format) {
            OutputContextInterface::FORMAT_LLMS_TXT      => $this->config->isLlmsTxtEnabled($store),
            OutputContextInterface::FORMAT_LLMS_FULL_TXT => $this->config->isLlmsFullTxtEnabled($store),
            OutputContextInterface::FORMAT_JSONL         => $this->config->isJsonlEnabled($store),
            default => false,
        };
    }

    private function deleteIfExists(WriteInterface $directory, string $relativePath): void
    {
        try {
            if ($directory->isExist($relativePath)) {
                $directory->delete($relativePath);
            }
        } catch (\Throwable $e) {
            $this->logger->warning(sprintf(
                '[Angeo LlmsTxt] Could not delete %s: %s',
                $relativePath,
                $e->getMessage()
            ));
        }
    }

    /**
     * @return resource|null
     */
    private function acquireLock(WriteInterface $directory, string $lockPath): mixed
    {
        $absolute = $directory->getAbsolutePath($lockPath);
        $parent = dirname($lockPath);
        if (!$directory->isExist($parent)) {
            $directory->create($parent);
        }
        $handle = fopen($absolute, 'c+');
        if ($handle === false) {
            return null;
        }
        if (!flock($handle, LOCK_EX | LOCK_NB)) {
            fclose($handle);
            return null;
        }
        return $handle;
    }

    /**
     * @param resource|null $handle
     */
    private function releaseLock(WriteInterface $directory, string $lockPath, mixed $handle): void
    {
        if (is_resource($handle)) {
            flock($handle, LOCK_UN);
            fclose($handle);
        }
        $this->deleteIfExists($directory, $lockPath);
    }
}
